apiVersion: v1
kind: ServiceAccount
metadata:
  name: fwegress 
  namespace: tailscale
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fwegress
  namespace: tailscale
rules:
- apiGroups:
    - "discovery.k8s.io"
  resources:
    - endpointslices
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - ""
  resources:
    - pods
    - pods/status
  verbs:
    - get
    - list
    - watch
    - update
    - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: fwegress 
    namespace: tailscale
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: fwegress
subjects:
    - kind: ServiceAccount
      name: fwegress 
      namespace: tailscale