blank_issues_enabled: true
contact_links:
  - name: Support and Product Questions
    url: https://tailscale.com/kb/1023/troubleshooting
    about: Please send support questions and questions about the Tailscale product to support@tailscale.com
