apiVersion: v1
kind: ServiceAccount
metadata:
  name: proxies
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
--
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
