apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: prod
spec:
  statefulSet:
    pod:
     spec:
       nodeSelector:
          beta.kubernetes.io/os: "linux"
       imagePullSecrets:
       - name: "foo"
