name: Windows race

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: windows-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Restore Cache
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Test with -race flag
      # Don't use -bench=. -benchtime=1x.
      # Somewhere in the layers (powershell?)
      # the equals signs cause great confusion.
      run: go test -race -count=100000 -run=TestPipeTimeout -timeout=100h ./net/nettest
